blueprint:
  name: Automated Daily Snapshot
  description: Create a full snapshot backup at a given time every day.
  source_url: https://raw.githubusercontent.com/EnvillePlease/HA-Housekeeping/main/ha-housekeeping.yaml
  domain: automation
  input:
    trigger_time:
      name: Snapshot creation time
      description: The snapshot will be created at this time, every day
      selector:
        time:
    send_notification:
      name: Send notification
      description: Sends a notification to a device if enabled
      selector:
        boolean:
      default: false
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications
      selector:
        device:
          integration: mobile_app
      default: ""

mode: single
max_exceeded: silent

variables:
  backup_filename: "Automated backup {{ now().strftime('%F') }}"
  backup_password_required: !input password_required
  backup_password: "Password"
  reboot_homeassistant: !input reboot
  send_notification: !input send_notification
  notify_device: !input notify_device
  notification_title: Automated Daily Backup
  notification_message: "Home Assistant full backup created. {{ now().strftime('%F') }}"

trigger:
  - platform: time
    at: !input trigger_time

action:
  - choose:
     - conditions: "{{ password_required }}"
       sequence:
          - service: hassio.backup_full
            data:
            name: "{{ backup_filename }}"
            password: "{{ backup_password }}"
       default:
       - service: hassio.backup_full
         data:
         name: "{{ backup_filename }}"
       
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
      
  - service: recorder.purge
    data:
      keep_days: 5
      repack: true
      
  - service: deconz.device_refresh
    data: {}
    
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0

  - choose:
      - conditions: "{{ send_notification }}"
        sequence:
          - device_id: !input notify_device 
            domain: mobile_app
            type: notify
            title: "{{ notification_title }}"
            message: "{{ notification_message }}"

  - choose:
      - conditions: "{{ reboot }}"
        sequence:
        - service: homeassistant.restart
          data: {}
